name: Backwards Compability Suite

on: [workflow_dispatch]

jobs:
  last-supported-major-to-current:
    name: Make sure that the last supported major version can move to the most current version
    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Checkout Security Repo
      uses: actions/checkout@v2

    - id: build-previous
      uses: ./.github/actions/run-bwc-suite
      with:
        plugin-previous-branch: "1.3"
        plugin-next-branch: "2.x"
        report-artifact-name: BWC-Last-Supported-Major

  current-to-next-unreleased-major:
    name: Make sure that the current version is compatible with the next major version
    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Checkout Security Repo
      uses: actions/checkout@v2

    - id: build-previous
      uses: ./.github/actions/run-bwc-suite
      with:
        plugin-previous-branch: "2.x"
        plugin-next-branch: "main"
        report-artifact-name: BWC-Next-Major
